[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.reportlab"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"
